### ISSUE TITLE
Quick question on why Direct

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now-admin#30]
So I've noticed you're moving from next-right-now-admin in favor of Direct, but this is confusing to me, as far as I understood this project is an admin back-office for users, I can't see how Direct will fill that gap, my understanding is that Direct is a free alternative of GraphCMS, am I wrong or misunderstanding something here?

Thanks.

**Comment by Vadorequest** [comment]
I'm not really moving from one to the other. It's meant to become another "preset".

GraphCMS has its own limitations, Directus has other limitations. 

They're similar, as both are Headless CMS that provide a set of API, admin app and database. 
But they're also very different in their implementation, as Directus is OSS and can be used for free, and allows for much more behaviour flexibility, while GraphCMS is completely locked and proprietary.

This project (NRN-Admin) is only meant to showcase how to build an admin app based on a GraphQL API. I built it because GraphCMS doesn't support the concept of "multi-tenancy" yet, and isn't non-developer friendly either. 

The goal of NRN-Admin is to provide a customisable admin app to your customers, so that they can manage their own dataset with a friendly UI (based on react-admin). 
Directus is another alternative for that purpose, which seems more robust and battle-tested.

**Comment by samuelcastro** [comment]
ok that make sense.
